-- DMAS HS12
-- =========
--      Datamart

-- ------------------------------------------------------------------------------------
create or replace transient table DMAS.AOEC.DTAMART_HS12_TRANSACTIONS (
	ID NUMBER(38,0) autoincrement start 1 increment 1 noorder,
	TAB VARCHAR(16),
	SRC_ID NUMBER(38,0),
	CONTINENT varchar,
    COUNTRY_ID NUMBER(38,0),
	COUNTRY_ISO3 VARCHAR(3),
	PARTNER_CONTINENT varchar,
    PARTNER_COUNTRY_ID NUMBER(38,0),
	PARTNER_COUNTRY_ISO3 VARCHAR(3),
	YEAR NUMBER(38,0),
	PRODUCT_ID NUMBER(38,0),
	EXPORT_VALUE FLOAT,
	IMPORT_VALUE FLOAT,
	COI FLOAT,
	ECI FLOAT
);

alter table DMAS.AOEC.DTAMART_HS12_TRANSACTIONS add CONTINENT varchar;
alter table DMAS.AOEC.DTAMART_HS12_TRANSACTIONS add PARTNER_CONTINENT varchar;

create or replace view DMAS.AOEC.DTAMART_HS12_TX_C_C_Y(
	CONTINENT,
    COUNTRY_ISO3,
	PARTNER_CONTINENT,
	PARTNER_COUNTRY_ISO3,
	YEAR,
	EXPORT_VALUE
) as
    select CONTINENT,
           COUNTRY_ISO3,
           PARTNER_COUNTRY_ISO3,
           YEAR,
           sum(EXPORT_VALUE) as EXPORT_VALUE
        from DTAMART_HS12_TRANSACTIONS
        group by COUNTRY_ISO3, PARTNER_COUNTRY_ISO3, YEAR
;

update DMAS.AOEC.DTAMART_HS12_TRANSACTIONS
        set CONTINENT = y.GROUP_NAME
    from DMAS.AOEC.LOCATION_GROUP_MEMBER y
    where y.GROUP_TYPE = 'continent'
      and y.COUNTRY_ID = DTAMART_HS12_TRANSACTIONS.COUNTRY_ID
;

update DMAS.AOEC.DTAMART_HS12_TRANSACTIONS
        set PARTNER_CONTINENT = y.GROUP_NAME
    from DMAS.AOEC.LOCATION_GROUP_MEMBER y
    where y.GROUP_TYPE = 'continent'
      and y.COUNTRY_ID = DTAMART_HS12_TRANSACTIONS.PARTNER_COUNTRY_ID
;
